server:
  port: 8087
  servlet:
    context-path: '/poc-application'

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

application:
  refreshscope:
    ttl: 7000
    retry: 1